version: "3"

services:
  pgdb:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - pgdb-data:/var/lib/postgresql/data
  drupal:
    image: drupal
    ports:
      - "8082:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    depends_on:
      - pgdb

volumes:
  pgdb-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
