version: "3.1"

services:

  psql:
    image: postgres:10.4-alpine
    secrets:
      - psql-pw
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql-pw

  drupal:
    image: drupal:8.5.4-apache
    ports:
      - "8082:80"
    depends_on:
      - psql

secrets:
  psql-pw:
    external: true
