# If taking Docker Mastery, this is the same file you created in
# ./compose-assignment-2
# If taking Swarm Mastery, this is your starting point for adding secrets :)
# reminder, this needs to change to 3.1 version to use secrets!
version: "3.1"

services:

  drupal:
    image: drupal:8.5.4
    build: .
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes

  postgres:
    image: postgres:9.6
    secrets:
      - psql-pw
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/psql-pw
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:

secrets:
  psql-pw:
    external: true
